export const actionTypes = {
  ADD_TODO_HANDLER: 'ADD_TODO_HANDLER',
  REMOVE_TODO_HANDLER: 'REMOVE_TODO_HANDLER',
  UPDATE_TODO_HANDLER: 'UPDATE_TODO_HANDLER',
  GET_TODOS_HANDLER: 'GET_TODOS_HANDLER',
  SET_USER_INFO: 'SET_USER_INFO',
};
